// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6KuTS4Sc9qK47de2i9SgjsopwebgmRgg',
    appId: '1:372641825548:web:77f9175fea4fa354e57f29',
    messagingSenderId: '372641825548',
    projectId: 'nutritionapplication-23b5c',
    authDomain: 'nutritionapplication-23b5c.firebaseapp.com',
    storageBucket: 'nutritionapplication-23b5c.firebasestorage.app',
    measurementId: 'G-Q0D36M81NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYnnzQGyd07FRVHeVFU_Ptud5VWdxGkTY',
    appId: '1:372641825548:android:ac86ca3d91399a28e57f29',
    messagingSenderId: '372641825548',
    projectId: 'nutritionapplication-23b5c',
    storageBucket: 'nutritionapplication-23b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi6xqDJu5I9noO9aFih8Gs7xAljU_yMYM',
    appId: '1:372641825548:ios:0fe3b55f6dec3bc2e57f29',
    messagingSenderId: '372641825548',
    projectId: 'nutritionapplication-23b5c',
    storageBucket: 'nutritionapplication-23b5c.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi6xqDJu5I9noO9aFih8Gs7xAljU_yMYM',
    appId: '1:372641825548:ios:0fe3b55f6dec3bc2e57f29',
    messagingSenderId: '372641825548',
    projectId: 'nutritionapplication-23b5c',
    storageBucket: 'nutritionapplication-23b5c.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6KuTS4Sc9qK47de2i9SgjsopwebgmRgg',
    appId: '1:372641825548:web:290eecf4c36eaae4e57f29',
    messagingSenderId: '372641825548',
    projectId: 'nutritionapplication-23b5c',
    authDomain: 'nutritionapplication-23b5c.firebaseapp.com',
    storageBucket: 'nutritionapplication-23b5c.firebasestorage.app',
    measurementId: 'G-88XPH17DNN',
  );
}
